name: study_pal_frontend
publish_to: none
description: studyPalのスマホアプリ
version: 1.0.0+1

assets:
  - assets/fonts/

fonts:
  - family: Lato
    fonts:
      - asset: assets/fonts/Lato/Lato-Thin.ttf
        weight: 100
      - asset: assets/fonts/Lato/Lato-Light.ttf
        weight: 300
      - asset: assets/fonts/Lato/Lato-Regular.ttf
        weight: 400
      - asset: assets/fonts/Lato/Lato-Bold.ttf
        weight: 700
      - asset: assets/fonts/Lato/Lato-Black.ttf
        weight: 900

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  hooks_riverpod: ^2.6.1
  built_collection: ^5.1.1
  dio: ^5.8.0+1
  openapi_generator_annotations: ^6.1.0
  openapi:
    path: ./openapi
  freezed_annotation: ^3.0.0
  flutter_riverpod: ^2.6.1
  very_good_infinite_list: ^0.9.0
  go_router: ^15.2.4
  formz: ^0.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.8
  freezed: ^3.0.0
flutter:
  uses-material-design: true
